#!/usr/bin/env python3
"""
review-ticket - Fetch a Linear ticket and check its claims against the
actual codebase before anyone plans or implements against it.

Deliberately standalone: not called by check-ticket.py, resolve-ticket.py,
or pipeline_lib.py, and does not write .ticket.md or any other pipeline
state file. This is a human-facing report, not a pipeline step - it never
rewrites the ticket and never feeds its own output into plan/narrow. Run
it on its own, read the report, fix the ticket in Linear yourself if it
flags something, then run check-ticket/resolve-ticket normally.

Why this exists: benchmarking the plan step surfaced that some "model
failures" were actually fixture/ticket-quality problems - acceptance
criteria that pre-stated their own answer, or described work that was
already fully implemented. The fix for that isn't a better plan prompt;
it's catching it before the ticket reaches plan at all (see BENCHMARKS.md,
sa501/sa502).

Uses opencode zen (see ai_client.py) via the read-only tool layer (see
tools.py: read_file, list_dir, search_files - no MCP, no write_file). The
model verifies the ticket's claims itself; nothing here trusts the
ticket's wording over the actual repository.

Saves the ticket text it reviewed plus the report to
.ticket-review-{ticket_id}.md - a local artifact only (never sent to
Linear), so propose-ticket-edit.py can later read exactly what was
reviewed without re-fetching (and risking the live ticket having
changed in between) or requiring you to paste the report between
terminals.

Reentrant via --ticket-file-in: pass propose-ticket-edit.py's
--ticket-file-out back in to re-review the proposed edit instead of
re-fetching the original from Linear, so you can loop
review -> propose -> review manually until a review comes back clean,
e.g.:

    review-ticket SA-42
    propose-ticket-edit SA-42 --ticket-file-out .ticket-proposed-SA-42.md
    review-ticket SA-42 --ticket-file-in .ticket-proposed-SA-42.md
    propose-ticket-edit SA-42 --ticket-file-out .ticket-proposed-SA-42.md
    ...repeat until review-ticket reports no concerns...
    update-ticket SA-42 --ticket-file-in .ticket-proposed-SA-42.md --yes

--ticket-file-in is the same flag name check-ticket.py/resolve-ticket.py/
write-tests.py/update-ticket.py use for "read the ticket from this local
file instead of Linear" - kept consistent across every script in this
set rather than each picking its own name for the same idea.

Usage:
    review-ticket <ticket-id> [--model <model-id>] [--ticket-file-in <path>]
"""

import argparse
import re
from datetime import datetime, timezone
from pathlib import Path

from .lib import ai_client, pipeline_lib as lib, render, tools, verbosity

log = verbosity.get_logger(__name__)

DEFAULT_MODEL = "opencode:gpt-5.4-mini"

VERDICT_LINE_RE = re.compile(r"(^###\s*Verdict\s*\n+)(\S+)", re.MULTILINE)

# Forced regardless of what the AI review step itself concluded - see
# apply_mechanical_grounding.
GROUNDING_OVERRIDE_VERDICT = "needs-attention"

REVIEW_PROMPT_FILE = lib.PROMPTS_DIR / "review-ticket.prompt.md"

# Not a real on-disk path - used only as a dedup key so a model that
# tries to read_file the ticket back after it was already embedded in
# the prompt gets the short "you already have this" note instead of a
# file-not-found error. Mirrors build_plan_prompt's preloaded_paths use
# of TICKET_FILE, but this script never writes that file to disk -
# review-ticket is intentionally decoupled from the other scripts'
# .ticket.md/.tdd-plan.md handoff convention.
TICKET_DEDUP_KEY = ".ticket.md"

# Markers used to round-trip the saved file - propose-ticket-edit.py
# splits on these exact strings, so keep them in sync if either changes.
REVIEW_FILE_TICKET_MARKER = "## Reviewed Ticket"
REVIEW_FILE_REPORT_MARKER = "## Ticket Review"


def review_file_path(ticket_id: str) -> Path:
    return Path(f".ticket-review-{ticket_id}.md")


def save_review(ticket_id: str, ticket_content: str, report: str) -> Path:
    path = review_file_path(ticket_id)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path.write_text(
        f"<!-- generated by review-ticket.py on {timestamp} for {ticket_id} -->\n\n"
        f"{REVIEW_FILE_TICKET_MARKER}\n\n{ticket_content}\n\n"
        f"{report}\n",
        encoding="utf-8",
    )
    return path


def build_review_prompt(ticket_content: str, prefetch_block: str) -> str:
    instructions = lib.load_prompt_body(REVIEW_PROMPT_FILE)
    prefetch_section = f"\n\n{prefetch_block}" if prefetch_block else ""
    return (
        f"{instructions}\n\n---\n\n"
        f"Here is the ticket - already complete and current, no need to "
        f"read_file it again:\n\n{ticket_content}{prefetch_section}\n\n"
        f"Use read_file/list_dir/search_files to verify the ticket's "
        f"claims against the actual codebase - but only for files/symbols "
        f"you have a concrete reason to check, not speculative browsing. "
        f"Produce the report in the exact format from Step 5 above. Your "
        f"final response (no further tool calls) must be exactly that "
        f"report - no chat header, no preamble or trailing commentary."
    )


def run_review_step(ticket_content: str, model: str) -> str:
    # Most of the files a ticket needs checked against are the ones it
    # names by path - prefetching those up front saves the model the
    # read_file turns (and the turn-count variance that comes with a
    # weaker model not always getting around to asking promptly - see
    # the loop-ticket-review.py 40-turn aborts this was built to address).
    prefetch_block, prefetch_paths = lib.prefetch_referenced_files(ticket_content)
    try:
        result = lib.run_ai_step_with_retry(
            lambda: ai_client.run_with_tools(
                build_review_prompt(ticket_content, prefetch_block),
                tools.READ_ONLY_TOOLS,
                tools.make_executor(
                    allow_write=False,
                    preloaded_paths={TICKET_DEDUP_KEY} | prefetch_paths,
                ),
                "review-ticket",
                model=model,
                summarize_call=tools.summarize_tool_call,
            ),
            "review-ticket",
        )
    except (ai_client.AIError, tools.PipelineAbort) as e:
        lib.die(str(e))
    if "## Ticket Review" not in result.text:
        lib.render_step_output(result.text, level=0)
        lib.die("Reviewer did not produce a valid report (see output above).")
    return result.text


def apply_mechanical_grounding(ticket_id: str, ticket_content: str, report: str) -> str:
    """
    Runs the same mechanical grounding check every stack-frame call site
    uses (lib.verify_criterion_grounding) against the ticket's own
    acceptance-criteria bullets (lib.extract_acceptance_criteria - a
    no-op, returning report unchanged, if the raw ticket has no
    "## Acceptance Criteria" heading to check), and forces the verdict to
    GROUNDING_OVERRIDE_VERDICT if any fail - regardless of what the AI
    review step itself concluded.

    This exists because the AI step alone has already been observed to
    miss exactly this failure: SA-454's raw ticket text claimed invoices
    should map to an `Outstanding` status that was never a real
    InvoiceStatus variant, and review-ticket's AI step returned "clear"
    anyway, despite having codebase read access. A soft AI judgment call
    is not a reliable backstop for a fact a grep resolves in milliseconds,
    so this doesn't ask the model to try harder, it checks independently
    in Python and overrules the verdict if the two disagree.

    Appends a "### Mechanical Grounding" section (distinct from the AI's
    own "### Concerns", which this never edits) and rewrites the
    "### Verdict" line in place so any caller reading only that line
    sees the corrected verdict.
    Each failure is also recorded to lib.DECLINED_CRITERIA_FILE (origin
    "review-ticket") for visibility alongside every other grounding
    checkpoint, even though the ledger's is_declined skip won't
    necessarily match this exact wording again later - Narrower commonly
    rewords a criterion between the raw ticket and the gap plan it
    produces, so push_ticket's own grounding check (origin="ticket")
    still re-verifies independently rather than trusting this pass alone.
    """
    criteria = lib.extract_acceptance_criteria(ticket_content)
    failures: list[tuple[str, list[str]]] = []
    for criterion in criteria:
        reasons = lib.verify_criterion_grounding(criterion, lib.extract_existing_test_refs(criterion))
        if reasons:
            failures.append((criterion, reasons))
            lib.record_declined(ticket_id, criterion, "review-ticket", reasons)
    if not failures:
        return report

    section_lines = [
        "",
        "### Mechanical Grounding",
        "The following acceptance criteria reference terms that don't appear anywhere",
        "in the tracked codebase - checked mechanically, not by the AI review step above:",
        "",
    ]
    for criterion, reasons in failures:
        section_lines.append(f"- {criterion}")
        for reason in reasons:
            section_lines.append(f"  - {reason}")
    report_with_section = report.rstrip() + "\n" + "\n".join(section_lines) + "\n"

    return VERDICT_LINE_RE.sub(
        r"\g<1>" + GROUNDING_OVERRIDE_VERDICT, report_with_section, count=1,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch a Linear ticket and report concerns about its quality before planning against it.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("ticket_id", help="Linear ticket ID, e.g. NEB-42")
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"opencode zen model ID to use (default: {DEFAULT_MODEL}).",
    )
    parser.add_argument(
        "--ticket-file-in",
        type=Path,
        default=None,
        help="Review this local file instead of fetching from Linear - e.g. "
             "propose-ticket-edit.py's --ticket-file-out, to re-review a "
             "proposed revision without touching the live ticket.",
    )
    parser.add_argument(
        "--log-level",
        default="info",
        choices=list(verbosity.LEVELS),
        help="Console verbosity (default: info).",
    )
    args = parser.parse_args()
    verbosity.setup_logging(args.log_level)

    if args.ticket_file_in is not None:
        if not args.ticket_file_in.exists():
            lib.die(f"{args.ticket_file_in} not found.")
        render.print_line(f"-- Reviewing local file {args.ticket_file_in} instead of fetching {args.ticket_id} from Linear.")
        ticket_content = args.ticket_file_in.read_text(encoding="utf-8")
    else:
        ticket_content = lib.fetch_ticket_text(args.ticket_id)
    report = run_review_step(ticket_content, args.model)
    report = apply_mechanical_grounding(args.ticket_id, ticket_content, report)
    saved_path = save_review(args.ticket_id, ticket_content, report)

    render.print_line()
    render.print_line(f"-- Ticket review for {args.ticket_id}:")
    render.print_line()
    render.print_line(report)
    render.print_line()
    render.print_line(f"-- Saved to {saved_path} (read by propose-ticket-edit.py).")
    render.print_line(f"-- Token usage: {ai_client.usage}")


if __name__ == "__main__":
    main()
